docs: Cleanup README

diff --git a/bake b/bake
--- a/bake
+++ b/bake
@@ -16,7 +16,7 @@
 # Learn more about it [on GitHub](https://github.com/hyperupcall/bake)
 
 if [ "$0" != "${BASH_SOURCE[0]}" ] && [ "$BAKE_INTERNAL_CAN_SOURCE" != 'yes' ]; then
-	printf '%s\n' "Error: This file should not be sourced" >&2
+	printf '%s\n' 'Error: This file should not be sourced' >&2
 	return 1
 fi
 
@@ -57,7 +57,7 @@ bake.info() {
 }
 
 # @description Dies if any of the supplied variables are empty. Deprecated in favor of 'bake.assert_not_empty'
-# @arg $@ string Variable names to print
+# @arg $@ string Names of variables to check for emptiness
 # @see bake.assert_not_empty
 bake.assert_nonempty() {
 	__bake_internal_warn "Function 'bake.assert_nonempty' is deprecated. Please use 'bake.assert_not_empty' instead"
@@ -65,7 +65,7 @@ bake.assert_nonempty() {
 }
 
 # @description Dies if any of the supplied variables are empty
-# @arg $@ string Variable names to print
+# @arg $@ string Names of variables to check for emptiness
 bake.assert_not_empty() {
 	local variable_name=
 	for variable_name; do
@@ -78,7 +78,7 @@ bake.assert_not_empty() {
 }
 
 # @description Dies if a command cannot be found
-# @arg $1 string Command to test for existence
+# @arg $1 string Command name to test for existence
 bake.assert_cmd() {
 	local cmd=$1
 
@@ -91,16 +91,30 @@ bake.assert_cmd() {
 	fi
 }
 
-# @description Edit configuration that affects the behavior of Bake
-# @arg $1 string Configuration option to change
-# @arg $2 string Value of configuration property
+# @description Change the behavior of Bake. See [guide.md](./docs/guide.md) for details
+# @arg $1 string Name of config property to change
+# @arg $2 string New value of config property
 bake.cfg() {
 	local cfg=$1
 	local value=$2
 
 	case $cfg in
-		stacktrace)
-			__bake_cfg_stacktrace=$value
+	stacktrace)
+		case $value in
+			yes|no) __bake_cfg_stacktrace=$value ;;
+			*) __bake_internal_die2 "Config property '$cfg' accepts only either 'yes' or 'no'" ;;
+		esac
+		;;
+	pedantic-task-cd)
+		case $value in
+			yes) trap '__bake_trap_debug' 'DEBUG' ;;
+			no) trap - 'DEBUG' ;;
+			*) __bake_internal_die2 "Config property '$cfg' accepts only either 'yes' or 'no'" ;;
+		esac
+		;;
+	*)
+		__bake_internal_die2 "No config property matched '$cfg'"
+		;;
 	esac
 }
 
@@ -115,23 +129,37 @@ __bake_print_stacktrace() {
 		fi
 
 		local i=
-		for ((i=0; i<${#FUNCNAME[@]}-1; i++)); do
-			local __bash_source=${BASH_SOURCE[$i]}; __bash_source="${__bash_source##*/}"
+		for ((i=0; i<${#FUNCNAME[@]}-1; ++i)); do
+			local __bash_source="${BASH_SOURCE[$i]}"; __bash_source=${__bash_source##*/}
 			printf '%s\n' "  in ${FUNCNAME[$i]} ($__bash_source:${BASH_LINENO[$i-1]})"
 		done; unset -v i __bash_source
 	fi
 } >&2
 
-# @description Function 'trap' calls on 'ERR'
+# @description Function that is executed when the 'ERR' event is trapped
 # @internal
 __bake_trap_err() {
 	local error_code=$?
 
 	__bake_print_big "<- ERROR"
-	__bake_internal_error "Your 'Bakefile.sh' did not exit successfully"
+	__bake_internal_error "Your Bakefile did not exit successfully (exit code $error_code)"
 	__bake_print_stacktrace
 
 	exit $error_code
+} >&2
+
+__global_bake_trap_debug_current_function=
+__bake_trap_debug() {
+	local current_function="${FUNCNAME[1]}"
+
+	if [[ $current_function != "$__global_bake_trap_debug_current_function" \
+			&& $current_function == task.* ]]; then
+		if ! cd "$BAKE_ROOT"; then
+			__bake_internal_die "Failed to cd to \$BAKE_ROOT"
+		fi
+	fi
+
+	__global_bake_trap_debug_current_function=$current_function
 } >&2
 
 # @description Test whether color should be outputed
@@ -144,6 +172,25 @@ __bake_is_color() {
 	else
 		return 0
 	fi
+}
+
+# @description Calls `__bake_internal_error` and terminates with code 1
+# @arg $1 string Text to print
+# @internal
+__bake_internal_die() {
+	__bake_internal_error "$1. Exiting"
+	exit 1
+}
+
+# @description Calls `__bake_internal_error` and terminates with code 1. Before
+# doing so, it closes with "<- ERROR" big text
+# @arg $1 string Text to print
+# @internal
+__bake_internal_die2() {
+	__bake_print_big '<- ERROR'
+
+	__bake_internal_error "$1. Exiting"
+	exit 1
 }
 
 # @description Prints `$1` formatted as an internal Bake error to standard error
@@ -168,15 +215,8 @@ __bake_internal_warn() {
 	fi
 } >&2
 
-# @description Calls `__bake_internal_error` and terminates with code 1
-# @arg $1 string Text to print
-# @internal
-__bake_internal_die() {
-	__bake_internal_error "$1. Exiting"
-	exit 1
-}
-
-# @description Prints `$1` formatted as an error to standard error
+# @description Prints `$1` formatted as an error to standard error. This is not called because
+# I do not wish to surface a public 'bake.error' function. All errors should halt execution
 # @arg $1 string Text to print
 # @internal
 __bake_error() {
@@ -187,18 +227,30 @@ __bake_error() {
 	fi
 } >&2
 
-# @description Nicely prints all 'Basalt.sh' tasks to standard output
+# @description Nicely prints all 'Bakefile.sh' tasks to standard output
 # @internal
 __bake_print_tasks() {
+	printf '%s\n' 'Tasks:'
+	local str=
+
 	# shellcheck disable=SC1007,SC2034
 	local regex="^(([[:space:]]*function[[:space:]]*)?task\.(.*?)\(\)).*"
 	local line=
-	printf '%s\n' 'Tasks:'
 	while IFS= read -r line || [ -n "$line" ]; do
 		if [[ "$line" =~ $regex ]]; then
-			printf '%s\n' "  -> ${BASH_REMATCH[3]}"
+			str+="  -> ${BASH_REMATCH[3]}"$'\n'
 		fi
 	done < "$BAKE_FILE"; unset -v line
+
+	if [ -z "$str" ]; then
+		if __bake_is_color; then
+			str=$'  \033[3mno tasks\033[0m\n'
+		else
+			str=$'  no tasks\n'
+		fi
+	fi
+
+	printf '%s' "$str"
 } >&2
 
 # @description Prints text that takes up the whole terminal width
@@ -228,16 +280,21 @@ __bake_print_big() {
 	fi
 } >&2
 
-__bake_set_vars() {
+# @description Parses the arguments. This also includes setting the the 'BAKE_ROOT'
+# and 'BAKE_FILE' variables
+# @set REPLY Number of times to shift
+# @internal
+__bake_parse_args() {
 	unset REPLY; REPLY=
 	local -i total_shifts=0
 
+	# FIXME: bug for when passing -v to child task argument
 	local __bake_arg=
 	for arg; do case $arg in
 	-f)
 		BAKE_FILE=$2
 		if [ -z "$BAKE_FILE" ]; then
-			__bake_internal_die 'File must not be empty. Exiting'
+			__bake_internal_die "A value was not specified for for flag '-f"
 		fi
 		((total_shifts += 2))
 		if ! shift 2; then
@@ -248,8 +305,12 @@ __bake_set_vars() {
 			__bake_internal_die "Specified file '$BAKE_FILE' does not exist"
 		fi
 		if [ ! -f "$BAKE_FILE" ]; then
-			__bake_internal_die "Specified path '$BAKE_FILE' is not actually a file"
+			__bake_internal_die "Specified file '$BAKE_FILE' is not actually a file"
 		fi
+		;;
+	-v)
+		local bake_version='1.7.0'
+		printf '%s\n' "Version: $bake_version"
 		;;
 	-h)
 		local flag_help='yes'
@@ -267,7 +328,7 @@ __bake_set_vars() {
 		BAKE_FILE="$BAKE_ROOT/${BAKE_FILE##*/}"
 	else
 		if ! BAKE_ROOT=$(
-			while [ ! -f 'Bakefile.sh' ] && [ "$PWD" != / ]; do
+			while [ ! -f './Bakefile.sh' ] && [ "$PWD" != / ]; do
 				if ! cd ..; then
 					exit 1
 				fi
@@ -279,14 +340,14 @@ __bake_set_vars() {
 
 			printf '%s' "$PWD"
 		); then
-			__bake_internal_die "Could not find 'Bakefile.sh'"
+			__bake_internal_die "Failed to find 'Bakefile.sh'"
 		fi
 		BAKE_FILE="$BAKE_ROOT/Bakefile.sh"
 	fi
 
 	if [ "$flag_help" = 'yes' ]; then
-		cat <<-EOF
-		Usage: bake [-h] [-f <Bakefile>] [var=value ...] <task> [args ...]
+		cat <<-"EOF"
+		Usage: bake [-h|-v] [-f <Bakefile>] [var=value ...] <task> [args ...]
 		EOF
 		__bake_print_tasks
 		exit
@@ -295,18 +356,22 @@ __bake_set_vars() {
 	REPLY=$total_shifts
 }
 
+# @description Main function
+# @internal
 __bake_main() {
-	__bake_cfg_stacktrace='yes'
+	__bake_cfg_stacktrace='no'
 
-	set -Eeo pipefail
+	set -ETeo pipefail
 	shopt -s dotglob extglob globasciiranges globstar lastpipe shift_verbose
-	export LANG='C' LC_CTYPE='C' LC_NUMERIC='C' LC_TIME='C' LC_COLLATE='C' LC_MONETARY='C' LC_MESSAGES='C' \
-		LC_PAPER='C' LC_NAME='C' LC_ADDRESS='C' LC_TELEPHONE='C' LC_MEASUREMENT='C' LC_IDENTIFICATION='C' LC_ALL='C'
+	export LANG='C' LC_CTYPE='C' LC_NUMERIC='C' LC_TIME='C' LC_COLLATE='C' \
+		LC_MONETARY='C' LC_MESSAGES='C' LC_PAPER='C' LC_NAME='C' LC_ADDRESS='C' \
+		LC_TELEPHONE='C' LC_MEASUREMENT='C' LC_IDENTIFICATION='C' LC_ALL='C'
 	trap '__bake_trap_err' 'ERR'
+	bake.cfg pedantic-task-cd 'no'
 
 	# Set `BAKE_{ROOT,FILE}`
 	BAKE_ROOT=; BAKE_FILE=
-	__bake_set_vars "$@"
+	__bake_parse_args "$@"
 	if ! shift "$REPLY"; then
 		__bake_internal_die 'Failed to shift'
 	fi
